import type { Metadata } from "next";
import "../globals.css";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import ReduxProvider from "@/libs/store/ReduxProvider";
import AutoLogin from "@/components/auth/AutoLogin";
import { cookies } from "next/headers";
import Script from "next/script";

export const metadata: Metadata = {
  title: "ArtEdu",
  description: "Generated by ArtEdu",
};

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const cookiesData = await cookies();
  const token = cookiesData.get("token");
  return (
    <html lang="en">
      <head>
        <Script
          id="organization-schema"
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "Organization",
              name: "ArtEdu",
              description: "{{ settings('meta_description_en') }}",
              telephone: "+2{{ settings('phone') }}",
              address: {
                "@type": "PostalAddress",
                streetAddress: "Downtown, Cairo, Egypt",
                addressLocality: "Cairo",
                addressRegion: "Cairo",
                postalCode: "11511",
                addressCountry: "Egypt",
              },
              url: "https://artedu-plum.vercel.app/",
              logo: "https://artedu-plum.vercel.app/logo.png",
              sameAs: [
                "https://www.facebook.com/artedu",
                "https://www.instagram.com/artedu",
                "https://www.linkedin.com/company/artedu",
              ],
            }),
          }}
        />
        <Script
          id="website-schema"
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "WebSite",
              name: "ArtEdu",
              url: "https://artedu-plum.vercel.app/",
              potentialAction: {
                "@type": "SearchAction",
                target: "https://artedu-plum.vercel.app/search?q={query}",
                "query-input": "required name=query",
              },
            }),
          }}
        />
      </head>
      <body className="relative">
        <ReduxProvider>
          <AutoLogin token={token?.value || null} />
          <div className=" mx-auto items-stretch  flex">
            <Navbar />
            <main className="w-full mt-[72px] md:mt-0 mx-auto h-full order-1 max-h-[100vh] overflow-auto hide-scrollbar">
              {children}
            </main>
          </div>
        </ReduxProvider>
        <Footer />
        <ToastContainer />
      </body>
    </html>
  );
}
