import type { Metadata } from "next";
import "../globals.css";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import ReduxProvider from "@/libs/store/ReduxProvider";
import AutoLogin from "@/components/auth/AutoLogin";

export const metadata: Metadata = {
  title: "ArtEdu",
  description: "Generated by ArtEdu",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className="relative">
        <ReduxProvider>
          <AutoLogin />
          <div className=" mx-auto items-stretch flex">
            <Navbar />
            <main className="w-full mx-auto order-1 max-h-[1200px] overflow-auto hide-scrollbar">
              {children}
            </main>
          </div>
          <ToastContainer />
        </ReduxProvider>
        <Footer />
      </body>
    </html>
  );
}
