import type { Metadata } from "next";
import "../globals.css";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import ReduxProvider from "@/libs/store/ReduxProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className="relative">
        <ReduxProvider>
          <div className=" max-w-[1920px] mx-auto  flex">
            <Navbar />
            <main className="w-full mx-auto order-1 h-screen max-h-[1080px] overflow-auto hide-scrollbar">
              {children}
            </main>
          </div>
          <ToastContainer />
        </ReduxProvider>
        <Footer />
      </body>
    </html>
  );
}
